### Neural Network

In [1]:
import torch


In [2]:
# Pick a manual seed for randomizations
torch.manual_seed(97)

In [3]:
# Create 4 random inputs and weights
input = torch.rand(4)
weight = torch.rand(4)
bias = 1

print(f"Input: {input}\nWeight: {weight}\nBias: {bias}")

Input: tensor([0.2577, 0.3639, 0.3804, 0.9233])
Weight: tensor([0.4714, 0.8464, 0.8527, 0.7252])
Bias: 1


In [4]:
# Neural Network
output = torch.matmul(input,weight) + bias
output

tensor(2.4235)

Layers of Neurons

In [5]:
input2 = torch.rand(4)
weight2 = torch.rand(size=(5, 4))
bias = torch.rand(5)

print(f"Input: {input2}\nWeights: {weight2}\nBias: {bias}")

Input: tensor([0.4314, 0.0768, 0.5296, 0.4009])
Weights: tensor([[0.9418, 0.9037, 0.8629, 0.4687],
        [0.3966, 0.5043, 0.3567, 0.1461],
        [0.3744, 0.9531, 0.5082, 0.3340],
        [0.9745, 0.2346, 0.9503, 0.7555],
        [0.7243, 0.7625, 0.8721, 0.5346]])
Bias: tensor([0.1671, 0.8678, 0.7120, 0.0442, 0.2787])


In [6]:
output2 = torch.matmul(input2, weight2.T) + bias

output2

tensor([1.2877, 1.3251, 1.3498, 1.2888, 1.3260])

In [7]:
input2 = output2
output_weight = torch.rand(size = (2, 5))
bias2 = torch.rand(2)

print(f"Input2: {input2}\nOutput_weight: {output_weight}\nBia2s: {bias2}")

Input2: tensor([1.2877, 1.3251, 1.3498, 1.2888, 1.3260])
Output_weight: tensor([[0.5170, 0.1564, 0.1337, 0.9721, 0.5814],
        [0.9412, 0.3896, 0.2498, 0.9929, 0.9158]])
Bia2s: tensor([0.8110, 0.6961])


In [8]:
final_output = torch.matmul(input2, output_weight.T) + bias2

final_output

tensor([3.8883, 5.2557])

Layer of Neurons & Batch of Data

In [9]:
inputs = torch.rand((32, 4))
weights = torch.rand((5, 4))
bias = torch.rand(5)

In [10]:
outputs = torch.matmul(inputs, weights.T) + bias

outputs

tensor([[1.7063, 0.9444, 2.8326, 2.3315, 0.8173],
        [1.7084, 0.9454, 2.1867, 1.5419, 1.0726],
        [1.4992, 0.8818, 2.1660, 1.3802, 0.8668],
        [1.9911, 0.9975, 2.6862, 2.0995, 1.1253],
        [1.5840, 1.1677, 2.5092, 2.0125, 1.0670],
        [2.1512, 1.2496, 3.2733, 2.5391, 1.2336],
        [1.3789, 0.7303, 1.7929, 1.5527, 0.8100],
        [1.8323, 0.8846, 2.5328, 1.6989, 0.9589],
        [1.7949, 0.9671, 2.6889, 2.1527, 0.9577],
        [1.1229, 0.5881, 1.7863, 1.0253, 0.4777],
        [2.2367, 1.0232, 2.9841, 2.3062, 1.2021],
        [1.7246, 0.9796, 3.0167, 2.3546, 0.7833],
        [2.1860, 1.2802, 3.2031, 2.4427, 1.3140],
        [1.6009, 0.9176, 2.7479, 1.8492, 0.7357],
        [1.3442, 0.6137, 1.9986, 1.4124, 0.5814],
        [1.8919, 0.8883, 2.8066, 2.2582, 0.9063],
        [1.5048, 0.9475, 2.3493, 1.6472, 0.8618],
        [1.7913, 1.0849, 3.0158, 2.3357, 0.9285],
        [1.8377, 1.0724, 2.4649, 1.9020, 1.1748],
        [1.3483, 0.8894, 2.0133, 1.7364, 0.8465],


Adding Layers

In [11]:
input_1 = torch.rand((32, 4))
weight_1 = torch.rand((5, 4))
bias_1 = torch.rand(5)

In [13]:
output_1 = torch.matmul(input_1, weight_1.T) + bias_1

In [14]:
input_layer_2 = output_1
weight_layer_2 = torch.rand(5, 5)
bias_2 = torch.rand(5)

In [15]:
output_layer_2 = torch.matmul(input_layer_2, weight_layer_2.T) + bias_2

In [16]:
input_final_layer = output_layer_2
weight_final_layer = torch.rand(3, 5)
bias_3 = torch.rand(3)

In [17]:
final_output = torch.matmul(input_final_layer, weight_final_layer.T) + bias_3

In [18]:
final_output

tensor([[16.9348, 17.3738, 14.2840],
        [14.5872, 14.9653, 12.3049],
        [13.7741, 14.1166, 11.6208],
        [14.7069, 15.0391, 12.4091],
        [18.3632, 18.9466, 15.4787],
        [12.8884, 13.1559, 10.8784],
        [16.4793, 16.9265, 13.8985],
        [14.0012, 14.3055, 11.8152],
        [15.6345, 16.0809, 13.1843],
        [15.8904, 16.3499, 13.3996],
        [15.5686, 15.9775, 13.1321],
        [17.2162, 17.6989, 14.5178],
        [11.8255, 11.9905,  9.9883],
        [17.3644, 17.7691, 14.6489],
        [17.2079, 17.6952, 14.5106],
        [14.6180, 14.8663, 12.3414],
        [15.6321, 16.0730, 13.1823],
        [14.1127, 14.3784, 11.9122],
        [15.6463, 16.0789, 13.1951],
        [16.8926, 17.3696, 14.2451],
        [16.7080, 17.2499, 14.0836],
        [16.3261, 16.7618, 13.7692],
        [15.2320, 15.6484, 12.8466],
        [12.5237, 12.7386, 10.5742],
        [13.1442, 13.3927, 11.0953],
        [14.4903, 14.8396, 12.2247],
        [15.8239, 16.2335, 13.3473],
 

 Neural Network with OOP

In [19]:
class DenseLayer:

  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weight = 0.01 * torch.rand((n_inputs, n_neurons))
    self.bias = torch.zeros(1, n_neurons)

  def forward(self, inputs):
    # calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weight) + self.bias

In [20]:
x = torch.rand((2, 4))

layer1 = DenseLayer(4, 6)
layer2 = DenseLayer(6, 5)
output_layer = DenseLayer(5, 2)

In [21]:
layer1.forward(x)
layer2.forward(layer1.output)
output_layer.forward(layer2.output)

In [22]:
output_layer.output

tensor([[4.2998e-06, 6.9072e-06],
        [1.0869e-05, 1.7512e-05]])

In [23]:
# Assignment


# Input layer (5 features)
# Hidden layers(3) with each layer containing 16 neurons
#  => H1
#  => H2
#  => H3
# output( 5 classes)

In [24]:
input_layer = torch.rand((30, 5))

In [25]:
layer1 = DenseLayer(5, 16)
layer2 = DenseLayer(16, 16)
layer3 = DenseLayer(16, 16)
output_layer = DenseLayer(16, 5)

In [26]:
layer1.forward(input_layer)
layer2.forward(layer1.output)
layer3.forward(layer2.output)
output_layer.forward(layer3.output)

In [27]:
output_layer.output

tensor([[2.9114e-06, 2.5782e-06, 3.8230e-06, 4.2621e-06, 3.8495e-06],
        [5.4605e-06, 4.8404e-06, 7.1760e-06, 7.9986e-06, 7.2225e-06],
        [3.8975e-06, 3.4496e-06, 5.1161e-06, 5.7056e-06, 5.1523e-06],
        [5.7859e-06, 5.1219e-06, 7.5996e-06, 8.4709e-06, 7.6480e-06],
        [6.3766e-06, 5.6471e-06, 8.3772e-06, 9.3375e-06, 8.4310e-06],
        [4.2695e-06, 3.7847e-06, 5.6116e-06, 6.2535e-06, 5.6470e-06],
        [4.7514e-06, 4.2047e-06, 6.2427e-06, 6.9593e-06, 6.2808e-06],
        [2.3057e-06, 2.0463e-06, 3.0293e-06, 3.3770e-06, 3.0518e-06],
        [3.9708e-06, 3.5238e-06, 5.2177e-06, 5.8149e-06, 5.2551e-06],
        [7.1668e-06, 6.3495e-06, 9.4167e-06, 1.0497e-05, 9.4779e-06],
        [3.6512e-06, 3.2341e-06, 4.7962e-06, 5.3465e-06, 4.8282e-06],
        [4.3107e-06, 3.8208e-06, 5.6617e-06, 6.3109e-06, 5.7019e-06],
        [4.4277e-06, 3.9245e-06, 5.8200e-06, 6.4843e-06, 5.8555e-06],
        [5.0053e-06, 4.4269e-06, 6.5715e-06, 7.3273e-06, 6.6144e-06],
        [4.1759e-06,

Other method

In [28]:
# Let's approach the assignment using an alternative method.

import torch.nn as nn
import torch.nn.functional as F


In [29]:
# Create a Model Class that inherits nn.Module
class Model(nn.Module):
  # Input layer (4 featues) -->
  # H1 or Hidden Layer1(number of neurons -->
  # H2 or Hidden Layer2(number of neurons -->
  # H3 or Hidden Layer3(number of neurons -->
  # output(5 class)

  def __init__(self,input_features=5,h1=16,h2=16,h3=16,output_features=5):
    super().__init__() # inistantiate out nn.Module
    self.fc1 = nn.Linear(input_features,h1)
    self.fc2 = nn.Linear(h1,h2)
    self.fc3 = nn.Linear(h2,h3)
    self.out = nn.Linear(h3,output_features)


  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = F.relu(self.fc3(x))
    x = self.out(x)

    return x


In [30]:
x = torch.rand((30, 5))

In [31]:
# Create an instance of model
model = Model()
model

Model(
  (fc1): Linear(in_features=5, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=16, bias=True)
  (out): Linear(in_features=16, out_features=5, bias=True)
)

In [32]:
model(x)

tensor([[-0.1258,  0.1699,  0.3513, -0.2028, -0.0976],
        [-0.1202,  0.1753,  0.3506, -0.2156, -0.0731],
        [-0.1328,  0.1604,  0.3250, -0.2086, -0.0732],
        [-0.1464,  0.1602,  0.3273, -0.1896, -0.0709],
        [-0.1206,  0.1793,  0.3547, -0.2169, -0.0714],
        [-0.1323,  0.1653,  0.3235, -0.2126, -0.0741],
        [-0.1479,  0.1603,  0.3499, -0.1869, -0.0753],
        [-0.1311,  0.1579,  0.3301, -0.2009, -0.0712],
        [-0.1390,  0.1652,  0.3375, -0.2006, -0.0693],
        [-0.1256,  0.1740,  0.3546, -0.2084, -0.0753],
        [-0.1394,  0.1666,  0.3326, -0.1932, -0.0621],
        [-0.1295,  0.1691,  0.3417, -0.2045, -0.0657],
        [-0.1240,  0.1638,  0.3643, -0.1938, -0.0955],
        [-0.1288,  0.1639,  0.3251, -0.2136, -0.0729],
        [-0.1152,  0.1841,  0.3542, -0.2234, -0.0682],
        [-0.1250,  0.1687,  0.3192, -0.2166, -0.0660],
        [-0.1234,  0.1687,  0.3588, -0.2058, -0.0851],
        [-0.1229,  0.1647,  0.3410, -0.2080, -0.0766],
        [-